config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :destroy]
    resource :like, only: [:show, :create, :destroy]
  end

  resources :questions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :answers, only: [:index, :create, :destroy]
  end

  resources :accounts, only: [:index, :show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
    resources :followings, only: [:index]
    resources :followers, only: [:index]
  end

  resources :favorites,     only: [:index]
  resources :populars,      only: [:index]
  resources :search,        only: [:index]
  resources :tags,          only: [:index]
  resources :taglists,      only: [:index]
  resources :prefectures,   only: [:index]
  resources :timelines,     only: [:index]
  resources :messages,      only: [:create]
  resources :rooms,         only: [:create, :show, :index]
  resource  :profile,       only: [:show, :update]
  resources :notifications, only: [:index]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower,  class_name: 'User'
  belongs_to :following, class_name: 'User'

  validates :following, uniqueness: { scope: :follower }
  validates :follower,  uniqueness: { scope: :following }
end

app/views/relationships/_follow.html.haml
= form_for(current_user, url: account_follows_path(@user), method: :post, remote: true) do |f|
  = hidden_field_tag :following_id, @user.id
  = f.submit "フォローする", class: "btn submit_btn"

app/views/relationships/_follow_form.haml
.follow_btn
  - if current_user&.has_followed?(@user)
    = render 'relationships/unfollow'
  - else
    = render 'relationships/follow'

app/views/relationships/_follow_form.html.haml
.follow_btn
  - if current_user&.has_followed?(@user)
    = render 'relationships/unfollow'
  - else
    = render 'relationships/follow'

app/views/relationships/_unfollow.html.haml
= form_for(current_user, url: account_unfollows_path(@user), method: :post, remote: true) do |f|
  = hidden_field_tag :following_id, @user.id 
  = f.submit 'フォロー解除', class: 'btn submit_btn'

app/views/relationships/follow.js.haml
$('#follow_form').html("#{ j(render 'relationships/unfollow') }")

app/views/relationships/unfollow.js.haml
$('#follow_form').html("#{ j(render 'relationships/follow') }")