config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :destroy]
    resource :like, only: [:show, :create, :destroy]
  end

  resources :questions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :answers, only: [:index, :create, :destroy]
  end

  resources :accounts, only: [:index, :show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
    resources :followings, only: [:index]
    resources :followers, only: [:index]
  end

  resources :favorites,     only: [:index]
  resources :populars,      only: [:index]
  resources :search,        only: [:index]
  resources :tags,          only: [:index]
  resources :taglists,      only: [:index]
  resources :prefectures,   only: [:index]
  resources :timelines,     only: [:index]
  resources :messages,      only: [:create]
  resources :rooms,         only: [:create, :show, :index]
  resource  :profile,       only: [:show, :update]
  resources :notifications, only: [:index]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope->{order(created_at: :desc)}

  belongs_to :post,      optional: true
  belongs_to :comment,   optional: true
  belongs_to :question,  optional: true
  belongs_to :answer,    optional: true
  belongs_to :room,      optional: true
  belongs_to :message,   optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.haml
- visitor = notification.visitor
- visited = notification.visited 
- post = notification.post

.notification
  = link_to account_path(visitor) do
    = image_tag visitor.avatar_image, class: 'msg_avatar'
    = visitor.username
  = 'さんが'

  - case notification.action
    - when 'follow' then
      = 'あなたをフォローしました'
    - when 'like' then
      = link_to 'あなたの投稿', notification.post
      = 'にいいねしました' 
    - when 'comment' then 
      - if notification.post.user_id == visited.id
        = link_to 'あなたの投稿', notification.post
      - else
        %span
          = link_to post_path(notification.post) do
            = image_tag visitor.avatar_image, class: 'msg_avatar'
            = notification.post.user.username + 'さんの投稿'
      = 'にコメントしました'
      %p.text-muted.mb-0
        = Comment.find_by(id: notification.comment_id)&.content
    - when 'answer' then 
      - if notification.question.user_id == visited.id
        = link_to 'あなたの質問', notification.question
      - else
        %span
          = link_to question_path(notification.question) do
            = image_tag visitor.avatar_image, class: 'msg_avatar'
            %strong
              = notification.question.user.username + 'さんの質問'
      = 'に回答しました'
      %p.text-muted.mb-0
        = Answer.find_by(id: notification.answer_id)&.content
    - when 'dm' then 
      - if notification.action == 'dm'
        = 'あなたに'
        = link_to 'ダイレクトメッセージ', room_path(notification.room)
        = 'を送りました'
        %p.text-muted.mb-0
          = Message.find_by(id: notification.message_id)&.content
  %span.notification_time_ago.text-muted= "(#{time_ago_in_words(notification.created_at)}前)"
  .clear 
  %hr

app/views/notifications/index.html.haml
.container
  %p.font-weight-bold 通知
  - if @notifications.exists?
    .users_index
      = render @notifications
      = paginate @notifications
  - else
    %p 通知はありません