config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :destroy]
    resource :like, only: [:show, :create, :destroy]
  end

  resources :questions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :answers, only: [:index, :create, :destroy]
  end

  resources :accounts, only: [:index, :show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
    resources :followings, only: [:index]
    resources :followers, only: [:index]
  end

  resources :favorites,     only: [:index]
  resources :populars,      only: [:index]
  resources :search,        only: [:index]
  resources :tags,          only: [:index]
  resources :taglists,      only: [:index]
  resources :prefectures,   only: [:index]
  resources :timelines,     only: [:index]
  resources :messages,      only: [:create]
  resources :rooms,         only: [:create, :show, :index]
  resource  :profile,       only: [:show, :update]
  resources :notifications, only: [:index]
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :content, presence: true

  has_many :notifications, dependent: :destroy

  belongs_to :user
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.user_id = current_user.id
    @answer_question = @answer.question
    if @answer.save!
      @answer_question.create_notification_answer!(current_user, @answer.id)
      render :index
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy!
    render :index
  end

  private
  def answer_params
    params.require(:answer).permit(:content, :question_id, :user_id)
  end

end

app/views/answers/_form.html.haml
= form_with(model: [question, answer] ) do |f|
  %div 
    = f.text_area :content, class: 'form comment_form answer_form'
  %div 
    = f.submit '回答', class: 'btn add_comment_btn submit_btn answer_form'

app/views/answers/_index.html.haml
- answers.each do |answer|
  .comment_container.clear 
    .user_info
      - if user_signed_in?
        - if answer.user.id == current_user.id
          = link_to profile_path do
            = image_tag answer.user.avatar_image, class: 'post_user_avatar'
            %p.post_user_name= answer.user.username
        - else 
          = render 'commons/user_info', post: answer
      - else 
        = render 'commons/user_info', post: answer 

    .comment_content 
      = simple_format(answer.content)
    - if answer.user == current_user 
      = link_to '回答を削除する', question_answer_path(answer.question_id, answer.id), data: { method: 'delete', confirm: '本当に削除してよろしいですか？' }, remote: true, class: 'comment_delete'

app/views/answers/index.js.haml
$('#answers_area').html("#{j(render 'index', { answers: @answer.question.answers })}")
$('textarea').val('')